version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - hobby_project_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    expose:
      - '5433'
    env_file:
      - ./.postgres.env

  api:
    container_name: app
    depends_on:
      - 'postgres'
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ['node']

volumes:
  hobby_project_db:
