version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - hobby_project_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    expose:
      - '5433'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    container_name: app
    depends_on:
      - 'postgres'
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ['node']

  rabbitmq:
    image: rabbitmq:3.9.1-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./definitions.json:/etc/rabbitmq/definitions.json

volumes:
  hobby_project_db:
  rabbitmqdata:
